# Dev profile — 最小可运行配置（便于本地与 IT 验证）

tfi:
  enabled: true
  change-tracking:
    enabled: true
    value-repr-max-length: 8192
    cleanup-interval-minutes: 0
    max-cached-classes: 1024
    debug-logging: true

# 可选：提升可观测性（开发环境）
logging:
  level:
    com.syy.taskflowinsight: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]

