# Prod profile — 保守默认（新功能关闭，可回滚）

tfi:
  enabled: false
  change-tracking:
    enabled: false
    value-repr-max-length: 8192
    cleanup-interval-minutes: 0
    max-cached-classes: 1024
    debug-logging: false

management:
  endpoints:
    web:
      exposure:
        include: ["health","info"]

logging:
  level:
    com.syy.taskflowinsight: INFO

